#############################################################################
# Makefile for building: p2papp
# Generated by qmake (2.01a) (Qt 4.8.0) on: Mon Nov 13 11:59:19 2017
# Project:  p2papp.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.0/bin/qmake -o Makefile p2papp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.8.0/include/QtCore -I/usr/local/Trolltech/Qt-4.8.0/include/QtNetwork -I/usr/local/Trolltech/Qt-4.8.0/include/QtGui -I/usr/local/Trolltech/Qt-4.8.0/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.0/lib -lQtGui -L/usr/local/Trolltech/Qt-4.8.0/lib -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc moc_main.cpp
OBJECTS       = main.o \
		moc_main.o
DIST          = Documentation \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		p2papp.pro
QMAKE_TARGET  = p2papp
DESTDIR       = 
TARGET        = p2papp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: p2papp.pro  /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile p2papp.pro
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile p2papp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/p2papp1.0.0 || $(MKDIR) .tmp/p2papp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/p2papp1.0.0/ && $(COPY_FILE) --parents main.hh .tmp/p2papp1.0.0/ && $(COPY_FILE) --parents main.cc .tmp/p2papp1.0.0/ && (cd `dirname .tmp/p2papp1.0.0` && $(TAR) p2papp1.0.0.tar p2papp1.0.0 && $(COMPRESS) p2papp1.0.0.tar) && $(MOVE) `dirname .tmp/p2papp1.0.0`/p2papp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/p2papp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp
moc_main.cpp: main.hh
	/usr/local/Trolltech/Qt-4.8.0/bin/moc $(DEFINES) $(INCPATH) main.hh -o moc_main.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cc main.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

