######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
DEFINES += QT_NO_DEBUG_OUTPUT
DEFINES += QT_NO_DEBUG
# Input
HEADERS += main.hh
SOURCES += main.cc

DISTFILES += \
    Documentation
